jsonschema in dockerfile added

diff --git a/bbx/run/default b/bbx/run/default
--- a/bbx/run/default
+++ b/bbx/run/default
@@ -1,10 +1,24 @@
 #!/bin/bash
 
+#check if file exists
+if [ ! -f /bbx/input/assembler.yaml ]
+then
+    printf 'No input data found at: "/bbx/input/assembler.yaml".' >&2 ; exit 1;
+fi
+
+#check if file is empty
+if [ ! -s /bbx/input/assembler.yaml ]
+then
+    printf 'Unable to parse: "/bbx/input/assembler.yaml".' >&2 ; exit 1;
+fi
+
 #validate yaml
-python /bbx/bin/schema_validator.py -i /bbx/input/assembler.yaml -s /bbx/schema/schema.yaml
+python /bbx/bin/schema_validator.py -i /bbx/input/assembler.yaml -s /bbx/schema/schema.json
 
 #if valid yaml run ray command
 if [ $? -eq  0 ]
 then	
 	python /bbx/bin/command_handler.py -i /bbx/input/assembler.yaml -o /bbx/output
+else
+    exit 1;
 fi
