assembler.yaml -> biobox.yaml

diff --git a/bbx/run/default b/bbx/run/default
--- a/bbx/run/default
+++ b/bbx/run/default
@@ -1,24 +1,24 @@
 #!/bin/bash
 
 #check if file exists
-if [ ! -f /bbx/input/assembler.yaml ]
+if [ ! -f /bbx/input/biobox.yaml ]
 then
-    printf 'No input data found at: "/bbx/input/assembler.yaml".' >&2 ; exit 1;
+    printf 'No input data found at: "/bbx/input/biobox.yaml".' >&2 ; exit 1;
 fi
 
 #check if file is empty
-if [ ! -s /bbx/input/assembler.yaml ]
+if [ ! -s /bbx/input/biobox.yaml ]
 then
-    printf 'Unable to parse: "/bbx/input/assembler.yaml".' >&2 ; exit 1;
+    printf 'Unable to parse: "/bbx/input/biobox.yaml".' >&2 ; exit 1;
 fi
 
 #validate yaml
-/bbx/bin/biobox-validator/validate-input --schema=/bbx/schema/schema.yaml --input=/bbx/input/assembler.yaml
+/bbx/bin/biobox-validator/validate-input --schema=/bbx/schema/schema.yaml --input=/bbx/input/biobox.yaml
 
 #if valid yaml run ray command
 if [ $? -eq  0 ]
 then	
-	python /bbx/bin/command_handler.py -i /bbx/input/assembler.yaml -o /bbx/output
+	python /bbx/bin/command_handler.py -i /bbx/input/biobox.yaml -o /bbx/output
 else
     exit 1;
 fi
